name: PR Create Webhook

on:
  pull_request:
    types: [opened]
    branches:
      - 'project/**'

jobs:
  notify-n8n:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send webhook to n8n
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_PR_CREATED_WEBHOOK_URL }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '${{ toJson(github.event) }}' \
            "${N8N_WEBHOOK_URL}"