name: PR Merge Webhook

on:
  pull_request:
    types: [closed]

jobs:
  notify-n8n:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Send webhook to n8n
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_PR_MERGED_WEBHOOK_URL }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '${{ toJson(github.event) }}' \
            "${N8N_WEBHOOK_URL}"